[pytest]
log_cli = 1
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S

minversion =  9.1.1
testpaths = tests
addopts =
    -v
    --alluredir=allure-results
    --tb=short
markers =
    positive: Тесты с валидными данными
    negative: Тесты с невалидными данными